import { test, expect } from '@playwright/test'
test('demo to audited cleaning, chat and download', async ({page}) => {
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Operations overview'})).toBeVisible()
  await page.getByRole('button',{name:'Explore demo workspace'}).click()
  await expect(page.getByText('Live dataset', {exact:true})).toBeVisible({timeout:30000})
  await page.getByRole('button',{name:'Preview cleaning',exact:true}).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByLabel('I reviewed the selected changes').check()
  await page.getByRole('button',{name:/Apply \d+ changes/}).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button',{name:'AI Copilot',exact:true}).click()
  await page.getByRole('button',{name:'Create a site-wise attendance chart'}).click()
  await expect(page.getByText('This chart uses computed values')).toBeVisible()
  await page.getByRole('button',{name:'Reports',exact:true}).click()
  const event = page.waitForEvent('download')
  await page.getByRole('button',{name:'Download CSV',exact:true}).click()
  expect((await event).suggestedFilename()).toContain('.csv')
})
test('mobile navigation stays inside viewport',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.getByRole('button',{name:'Open navigation'}).click()
  await page.getByRole('button',{name:'Data Sources',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Connect your data'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
})
