import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { ArrowDown, ArrowUpRight, ChevronLeft, ChevronRight, Search, X } from 'lucide-react'
import type { ChartSpec, Row } from './types'
const Chart=lazy(()=>import('./Chart'))
export const human=(s:string)=>s.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase())
export const num=(n:number|undefined)=>n===undefined?'—':n.toLocaleString('en-IN',{maximumFractionDigits:1})
export const display=(v:unknown)=>v===null||v===undefined||v===''?'—':String(v)
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}) {return <span className={`badge ${tone}`}>{children}</span>}
export function Panel({title,subtitle,action,children,className=''}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}>{title&&<div className="panel-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>}
export function ChartPanel({spec}:{spec:ChartSpec}) {return <Panel title={spec.title} subtitle={spec.subtitle} action={<ArrowUpRight size={17} className="muted"/>}><Suspense fallback={<div className="chart skeleton"/>}><Chart spec={spec}/></Suspense></Panel>}
export function DataTable({rows,columns,onRow,highlight}:{rows:Row[];columns?:string[];onRow?:(r:Row)=>void;highlight?:Set<number>}) {
  const [search,setSearch]=useState(''),[page,setPage]=useState(1),[sort,setSort]=useState(''),[desc,setDesc]=useState(false),[hidden,setHidden]=useState<string[]>([])
  const cols=columns||Object.keys(rows[0]||{}).filter(c=>!c.startsWith('_'))
  let data=rows.filter(r=>Object.values(r).some(v=>display(v).toLowerCase().includes(search.toLowerCase())))
  if(sort) data=[...data].sort((a,b)=>{const av=a[sort],bv=b[sort];return (typeof av==='number'&&typeof bv==='number'?av-bv:display(av).localeCompare(display(bv)))*(desc?-1:1)})
  const pages=Math.max(1,Math.ceil(data.length/12)),current=Math.min(page,pages)
  return <div className="ops-data-table-wrap"><div className="table-toolbar"><label className="search"><Search size={16}/><input id="dataset-search-input" aria-label="Search table" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search records…"/></label><details className="column-picker"><summary>Columns</summary><div>{cols.map(c=><label key={c}><input type="checkbox" checked={!hidden.includes(c)} onChange={()=>setHidden(hidden.includes(c)?hidden.filter(x=>x!==c):[...hidden,c])}/>{human(c)}</label>)}</div></details><span className="table-count-badge">{num(data.length)} records</span></div><div className="table-scroll"><table><thead><tr>{cols.filter(c=>!hidden.includes(c)).map(c=><th key={c}><button onClick={()=>{setSort(c);setDesc(sort===c?!desc:false)}}>{human(c)}{sort===c&&<ArrowDown size={12}/>}</button></th>)}</tr></thead><tbody>{data.slice((current-1)*12,current*12).map((r,i)=><tr key={i} className={highlight?.has(Number(r._source_row))?'flagged':''} onClick={()=>onRow?.(r)}>{cols.filter(c=>!hidden.includes(c)).map((c,j)=>{const raw=r[c],val=display(raw),isStatus=['attendance_status','status'].includes(c),isSeverity=c==='severity',isId=c.toLowerCase().includes('id')&&val!=='—',isPresent=String(raw).toLowerCase()==='present',isAbsent=String(raw).toLowerCase()==='absent';return <td key={c}>{j===0&&onRow?<button className="link-button" onClick={()=>onRow(r)}>{val}</button>:isStatus?<span className={`status-pill ${isPresent?'status-present':isAbsent?'status-absent':'status-neutral'}`}><span className="status-indicator-dot"/>{val}</span>:isSeverity?<Badge tone={raw==='critical'?'critical':raw==='warning'?'warning':'info'}>{val}</Badge>:isId?<code className="table-code-badge">{val}</code>:val==='—'?<span className="cell-missing">—</span>:<span title={val}>{val}</span>}</td>})}</tr>)}</tbody></table>{!data.length&&<div className="empty">No records match your search.</div>}</div><div className="pagination"><span>Showing {data.length?(current-1)*12+1:0}–{Math.min(current*12,data.length)} of {num(data.length)}</span><div><button className="icon-button" aria-label="Previous page" disabled={current===1} onClick={()=>setPage(current-1)}><ChevronLeft size={16}/></button><span>{current} / {pages}</span><button className="icon-button" aria-label="Next page" disabled={current===pages} onClick={()=>setPage(current+1)}><ChevronRight size={16}/></button></div></div></div>
}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}) {
  const ref=useRef<HTMLDialogElement>(null)
  useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close()},[])
  return <dialog className={`modal ${wide?'wide':''}`} ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="modal-head"><div><span className="eyebrow">OPSFLOW WORKSPACE</span><h2>{title}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>
}
