import { ArrowRight, ArrowUpRight, Check, CircleCheck, Database, FileSpreadsheet, GitBranch, Layers3, ShieldCheck, Sparkles, Upload, WandSparkles } from 'lucide-react'
import { motion } from 'framer-motion'
import type { Dataset, Summary } from './types'
import { Badge, ChartPanel, num, Panel } from './components'

export default function Overview({dataset,live,onUpload,onDemo,onClean,onNavigate,summary,onSummary,busy}:{dataset:Dataset;live:boolean;onUpload:()=>void;onDemo:()=>void;onClean:()=>void;onNavigate:(p:string)=>void;summary?:Summary;onSummary:()=>void;busy:boolean}) {
 const a=dataset.analysis,op=a.operations,issues=Object.values(a.severity).reduce((x,y)=>x+y,0)
 return <>
   <div className="context-banner"><span><span className="small-dot"/>{dataset.demo?'Prototype for Grace Facility Services · Synthetic facility data':'Grace Facility Services · Operations workspace'}<span className="banner-divider">/</span>{live?'Original source preserved':'Interactive operational prototype'}</span><Badge tone={live?'success':'neutral'}>{live?'Live dataset':'Grace Prototype'}</Badge></div>
   <section className="story-card"><div className="story-copy"><div className="eyebrow light"><span className="tiny-line"/> PROTOTYPE FOR GRACE FACILITY SERVICE · INTELLIGENCE FOR OPERATIONS</div><h2>Messy data.<br/><span>Clear decisions.</span></h2><p>Find the gaps. Review every change.<br/>Turn your spreadsheets into your next best action.</p><div className="story-buttons"><button className="button lime" onClick={onUpload}><Upload size={16}/>Analyze your data<ArrowUpRight size={16}/></button><button className="button story-ghost" onClick={onDemo} disabled={busy}>Explore demo workspace<ArrowRight size={15}/></button></div><div className="story-foot"><ShieldCheck size={13}/> Your originals stay untouched. Always.</div></div><div className="story-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="floating-file"><div className="art-file-icon"><FileSpreadsheet size={20}/></div><div><b>operations_september.xlsx</b><small>Raw data · Multiple formats</small></div><span className="art-dots">•••</span></div><div className="art-connector"><span/><Sparkles size={18}/><span/></div><div className="insight-preview"><div className="insight-label"><span className="live-spark"><Sparkles size={14}/></span>FROM DATA TO DIRECTION<Check size={16}/></div><div className="insight-body"><div><small>Ready for a closer look</small><strong>{num(a.safe_changes)}<span>safe changes</span></strong><div className="mini-bars">{[35,48,32,60,48,70,83,95].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div><div className="art-quality"><ShieldCheck size={28}/><span>REVIEW.<br/>THEN APPLY.</span></div></div></div><div className="art-chip"><CircleCheck size={14}/> Every change, traceable.</div></div></section>
  <div className="metrics-grid">{[{label:'Records analysed',value:num(a.rows),note:`Across ${a.columns} data fields`,icon:Database,tone:'green'},{label:'Issues detected',value:num(issues),note:`${a.severity.critical} need priority review`,icon:Layers3,tone:'amber'},{label:'Data quality',value:`${a.quality_score}%`,note:dataset.version?`Up from ${dataset.quality_before}% before review`:'A transparent, rule-based score',icon:ShieldCheck,tone:'green'},{label:'Safe improvements',value:num(a.safe_changes),note:'Ready for your review',icon:WandSparkles,tone:'green'}].map((m,i)=><motion.div className="metric-card" key={m.label} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.04,duration:.2}}><div className="metric-top"><span>{m.label}</span><m.icon size={17}/></div><strong>{m.value}</strong><span className={`metric-note ${m.tone}`}><span className="small-dot"/>{m.note}</span></motion.div>)}</div>
  <Panel className="journey"><div className="journey-title"><GitBranch size={17}/><div><h3>Your data journey</h3><p>Clarity at every step</p></div></div><div className="journey-steps">{['Source preserved','Schema understood','Issues detected','Cleaning reviewed','Decisions ready'].map((label,i)=><div className={`journey-step ${i<3||dataset.version?'complete':''}`} key={label}><span>{i<3||dataset.version?<Check size={12}/>:i+1}</span><small>{label}</small></div>)}</div><button className="text-button" onClick={onClean}>Review changes<ArrowRight size={14}/></button></Panel>
   <div className="overview-charts">{a.charts[0]&&<ChartPanel spec={a.charts[0]}/>}<Panel title="A clearer picture of your data" subtitle="Quality you can measure. Changes you can trust." action={<ShieldCheck size={18} className="muted"/>}><div className="quality-content"><div className="quality-ring" style={{'--score':`${a.quality_score}%`} as React.CSSProperties}><div><strong>{a.quality_score}<span>%</span></strong><small>QUALITY SCORE</small></div></div><div className="quality-breakdown"><div><span><i className="severity-dot critical"/>Urgent</span><strong>{num(a.severity.critical)}</strong></div><div><span><i className="severity-dot warning"/>Review needed</span><strong>{num(a.severity.warning)}</strong></div><div><span><i className="severity-dot info"/>Minor / Format</span><strong>{num(a.severity.info)}</strong></div><div className="before-after"><span>Before <b>{dataset.quality_before}%</b></span><ArrowRight size={14}/><span>Now <b>{a.quality_score}%</b></span></div></div></div><div className="panel-bottom"><span>{num(a.safe_changes)} improvements ready to preview</span><button className="text-button" onClick={onClean}>Preview cleaning<ArrowRight size={14}/></button></div></Panel></div>
   <div className="overview-bottom"><Panel title="Where your attention matters" subtitle="Priority operational exceptions, in one place" action={<button className="text-button" onClick={()=>onNavigate('Exceptions')}>View all<ArrowUpRight size={14}/></button>}><div className="attention-list">{op.sites.slice(0,3).map((s,i)=><button key={s.site} className="attention-row" onClick={()=>onNavigate('Analytics')}><span className="site-initial">{s.site.slice(0,2).toUpperCase()}</span><div><b>{s.site}</b><small>{num(s.gap)} uncovered staff-shifts · review coverage</small></div><Badge tone={i===0?'critical':'warning'}>{i===0?'Priority':'Review'}</Badge><ArrowUpRight size={15}/></button>)}{!op.available&&<p className="panel-text">{a.summary}</p>}</div><div className="panel-bottom"><ShieldCheck size={14}/><span>Demonstration rules · original records retained</span></div></Panel><Panel className="executive" title="Your executive brief" subtitle={summary?.provider==='deterministic'?'Instant summary · computed from data':summary?`AI Executive Brief · ${summary.provider}`:'Clear facts. Confident next steps.'} action={<Sparkles size={19}/>}><p className="executive-copy">{summary?.text||(op.sites[0]?`${op.sites[0].site} has the largest staffing gap across this period. Start with coverage, then review the ${a.severity.critical} critical data and operational issues before preparing your report.`:a.summary)}</p><div className="executive-footer"><span><i className="small-dot"/>Grounded in your data</span><button className="text-button" onClick={onSummary} disabled={busy}>{busy?'Preparing…':'Generate AI brief'}<ArrowRight size={14}/></button></div></Panel></div>
 </>
}
